import React from 'react'
import Head from 'next/head'

const Layout = ({ children, title = "Store demo" }) => {
     return (
          <div className="layout">

               <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>

               <div>
                    sidebar
               </div>
               <div className="layout-content">
                    <div>navbar</div>
                    <div className="layout-pages">{children}</div>
               </div>
          </div>
     )
}

export default React.memo(Layout)
