import { memo, useState } from 'react'
import Head from 'next/head'
import Sidebar from '../Sidebar'
import Navbar from '../Navbar'
import { Provider } from 'react-redux'
import store from '../../redux/store'

const Layout = ({ children, title = "GMarket" }) => {


     return (
          <Provider store={store}>
               <div className="layout">

                    <Head>
                         <title>{title}</title>
                         <meta name="description" content="Generated by create next app" />
                         <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
                         <link rel="icon" href="/favicon.ico" />
                    </Head>

                    <Sidebar />
                    <div className="layout-content">
                         <Navbar />
                         <div className="layout-pages">{children}</div>
                    </div>
               </div>
          </Provider>
     )
}

export default memo(Layout)
